// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS67Sf3Yz4-I1xLzctn5yb2Rrqdwuz2No',
    appId: '1:817067518210:web:dab42fe1e212fc74e03a1b',
    messagingSenderId: '817067518210',
    projectId: 'subash-app-cdb21',
    authDomain: 'subash-app-cdb21.firebaseapp.com',
    storageBucket: 'subash-app-cdb21.appspot.com',
    measurementId: 'G-5B1EDXRBTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx5S1xHFfOQVeE0dVfJ8FKtdC7adL-AO8',
    appId: '1:817067518210:android:43008c825058591ce03a1b',
    messagingSenderId: '817067518210',
    projectId: 'subash-app-cdb21',
    storageBucket: 'subash-app-cdb21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Djg-Ae1ghAIK8aM2DoDvBBeJPj3QW-s',
    appId: '1:817067518210:ios:a2c4670da355ea82e03a1b',
    messagingSenderId: '817067518210',
    projectId: 'subash-app-cdb21',
    storageBucket: 'subash-app-cdb21.appspot.com',
    iosBundleId: 'com.example.subhashApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Djg-Ae1ghAIK8aM2DoDvBBeJPj3QW-s',
    appId: '1:817067518210:ios:e3fc56fea58b6022e03a1b',
    messagingSenderId: '817067518210',
    projectId: 'subash-app-cdb21',
    storageBucket: 'subash-app-cdb21.appspot.com',
    iosBundleId: 'com.example.subhashApp.RunnerTests',
  );
}
